# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pM3abtlpUiLmMeZfV6iJkJpqL65QBwez
"""

item1=int(input())
item2=int(input())
item3=int(input())
cost=item1+item2+item3
if(cost>50):
  cost=0.9*cost
  print("Total amount after discount=",cost)
else:
  print("Total amount=",cost)